version: "3.9"
services:
  default:
    build:
      context: .
      args:
        ENV_TYPE: default
    ports:
      - "8888:8888" 
    volumes:
      - .:/app 
    environment:
      - PYTHONPATH=/app
    container_name: tydi_default
volumes:
  python_cache: 